server:
  port: 8766

spring:
    application:
        name: battcn-feign-hi22
    cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          enabled: true
          register: true
          health-check-path: /health2

#cloud:
#consul:
#host: localhost
#port: 8500
#enabled: true
#discovery:
#enabled: true
#prefer-ip-address: true